[workspace]
members = ["core", "prover", "sdk"]
resolver = "3"

[workspace.package]
version = "0.1.0"
repository = "https://github.com/zelana-labs/zelana"
homepage = "https://zelana.org/"
license = "Apache-2.0"
edition = "2024"

[workspace.dependencies]