[package]
name = "zelana-pubkey"
description = "Zelana Pubkey type"
version = {workspace = true}
edition = {workspace = true}

[dependencies]
serde = { workspace = true}
zelana-account = {workspace = true}
sha2 = {workspace = true}