[package]
name = "core"
version = { workspace = true }
edition = { workspace = true }

[[bin]]
name = "core"
path = "src/main.rs"

[dependencies]
solana-client = "3.1.3"
solana-sdk = "3.0.0"
solana-commitment-config = "3.1.0"
regex = "1.12.2"
rocksdb = "0.24"
tokio = { version = "1.48" }
tokio-stream = "0.1.17"
tokio-util = "0.7"
wincode = "0.2.1"
wincode-derive = "0.2.1"
ed25519-dalek = "2.2.0"
x25519-dalek = "2.0.1"
anyhow = "1.0.100"
dashmap = "5.5"                           # Concurrent HashMap for session management
log = "0.4"
env_logger = "0.10"
hex = { workspace = true }
chacha20poly1305 = "0.10"
sha2 = "0.10.9"
hkdf = "0.12"
zephyr = { workspace = true }
thiserror = { workspace = true }
blake3 = { workspace = true }
zelana-account = { workspace = true }
zelana-transaction = { workspace = true }
zelana-keypair = { workspace = true }

[dev-dependencies]
borsh = "1.6.0"
solana-program = "3.0.0"