[package]
name = "core"
version = {workspace = true}
edition = {workspace = true}

[[bin]]
name = "core"
path = "src/sequencer/main.rs"

[dependencies]
solana-client = "3.1.3"
solana-sdk = "3.0.0"
solana-commitment-config = "3.1.0"
regex = "1.12.2"
rocksdb = "0.24"
tokio = {version = "1.48"}
tokio-stream  = "0.1.17"
tokio-util = "0.7"
wincode = "0.2.1"
ed25519-dalek = "2.2.0"
x25519-dalek = "2.0.1"
anyhow = "1.0.100"
dashmap = "5.5" # Concurrent HashMap for session management
log = "0.4"
env_logger = "0.10"