[package]
name = "zelana-account"
description = "Zelana Account type"
version = {workspace = true}
edition = {workspace = true}

[dependencies]
serde = { workspace = true }
hex = {workspace = true}
wincode = { workspace = true }
wincode-derive = {workspace = true}
thiserror ={ workspace = true}