[package]
name = "zelana-account"
description = "Zelana account types"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
hex = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
wincode = { workspace = true , features = ["derive"]}
