apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zelana-prover

resources:
  - namespace.yaml
  - prover-nodes/statefulset.yaml
  - prover-nodes/service.yaml
  - coordinator/deployment.yaml
  - coordinator/service.yaml
  - coordinator/configmap.yaml

commonLabels:
  app.kubernetes.io/name: distributed-prover
  app.kubernetes.io/part-of: zelana