# Private inputs
spending_key = "18528047857356794251205269288273908325960775354190563366445424366525458198309"
note_value = "1000000000"
note_blinding = "60728701774391105801921528871564436323461687803288536276181160559144160672030"
note_position = "0"

# Public inputs
commitment = "112891777572701258296869557380583292241290542121405302794578408851974745713961"
nullifier = "44651246400605695142327358805872735147959963513440036549642194395572879397929"
blinded_proxy = "67670010842147849646502062978008384391026525065871139511345578704655181008649"
