amounts = ["", ""]
merkle_paths = [["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]]
new_root = ""
old_root = ""
receiver_pubkeys = ["", ""]
sender_pubkeys = ["", ""]
signatures = ["", ""]
